### ISSUE TITLE
Two different authority names

### ISSUE THREAD

**Issue by Carol-Sokolowicz** [plazi/community#15]
Hi Donat,

This is a zootaxa paper in which the treatment brings two different authorities:

![image](https://user-images.githubusercontent.com/57491712/77919191-3f7a3300-7273-11ea-9f76-029174e71272.png)

How should we proceed since both authorities would be linked to the species name in GBIF, isn't it wrong?

**Comment by myrmoteras** [comment]
which Zootaxa is this?

**Comment by Carol-Sokolowicz** [comment]
Sorry,
This one:
![image](https://user-images.githubusercontent.com/57491712/77919899-21610280-7274-11ea-9b15-cfac98e4f097.png)


DOI: 10.11646/zootaxa.4755.2.7
https://drive.google.com/open?id=11pkk88WAe9m5bvOEMvKnXqV6MykL37a3

**Comment by myrmoteras** [comment]
this is botanical style.

I would just take as authority (Andrassy, 1958)

**Comment by Carol-Sokolowicz** [comment]
Ok, but should I exclude Goodey, 1963 from the heading, because if don't both authors will be linked as authorities.

**Comment by myrmoteras** [comment]
in the edit taxononomicName menu, you only use Andrassy for authority and authorityName. 

Don't forget, we are not here to correct errors, but represent what we find.

**Comment by flsimoes** [comment]
Sorry to barge in the discussion, but in order to properly organize the treatment flow (include only Andrássy, 1958) you need to do a couple of things:
- assign Goodey, 1963 as a different paragraph (i.e. change the relationship of Goodey with the previous word)
- mark the heading as you want (up to "1958)")
- mark the treatment and subSubSections accordingly, with a split after "1958)"

Otherwise it is quite likely you will get a broken structure notification when you do the Quality Check.

**Comment by myrmoteras** [comment]
ok - If you do it this way, then type the subSubSection that includes Goodey as reference_group.

It is a treatmentCitation, thoug we miss the page number you still could also tag it as treatmentCiation that as as attributes authority, year, but not page number

**Comment by mguidoti** [comment]
You guys are suggesting two different strategies here, and I think we should go with Donat's one that alters only at attribute level because we do have the policy of keeping things as the authors presented and by editing only attributes, we would keep the treatment title as intended by the authors - regardless if it's right or wrong.

**Comment by mguidoti** [comment]
@Carol-Sokolowicz what's the status of this one?

Thanks
