### ISSUE TITLE
Treatment bank - Google maps perhaps broken based on version

### ISSUE THREAD

**Issue by mjy** [plazi/community#164]
When I:
* Navigate to http://treatment.plazi.org/id/3D0ED365FF8A5146DA3CFBBD4251FEC5
* Click on `Distribution` on the right
* Click on `GoogleMaps`
* Then I get a popupwindow, and it is empty.  
* And I get a message "GoogleMaps is not supported in this browser" (We tried most recent FF, FF Developer, Chrome and Safari)
* And we observe that there is a Javascript error in the console

<img width="631" alt="Screen Shot 2022-10-21 at 11 26 40 AM" src="https://user-images.githubusercontent.com/22600/197244090-ee1de722-a370-4e01-9b12-88f640b05fae.png">
<img width="1459" alt="Screen Shot 2022-10-21 at 11 27 05 AM" src="https://user-images.githubusercontent.com/22600/197244096-f63ecb8d-acf2-4f7d-b31b-183161bc3cab.png">

**Comment by flsimoes** [comment]
If I'm not mistaken there's an issue with the API key
@myrmoteras might have a say here

**Comment by gsautter** [comment]
This has been lingering for years without getting resolved ... I'd love to stick with GoogleMaps due to the satellite imagery, but we can also switch to a different map provider, including OpenStreetMap ... for GoogleMaps, we'll need to get an API key to get them working again.

There's other issues on this already: https://github.com/plazi/Plazi-Communications/issues/916 https://github.com/gsautter/goldengate-imagine/issues/794 https://github.com/plazi/treatmentBank/issues/51
as well as a (dormant) discussion page: https://github.com/plazi/Plazi-Communications/discussions/1166
