### ISSUE TITLE
tobe processed

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#21]
https://twitter.com/Publi_MNHN/status/1247464128064741376?s=09

**Comment by mguidoti** [comment]
We halted the Adansonia production due to the micro references in the `treatmentCitations`, which is common to botanical journals and can't be automated at this point, which generates lots and lots of manual editing per article.

But we can go forward with this one, in particular, especially because it has no `treatmentCitations`. 

@Carol-Sokolowicz could you please download @truschel Adansonia template, and, run an individual extraction on this paper after checking if the template was loaded? This shall get you a better result than just processing without a template.

Link straight to the paper: http://sciencepress.mnhn.fr/sites/default/files/articles/pdf/adansonia2020v42a6.pdf

**Comment by myrmoteras** [comment]
ok - we need to come up with a labeling sytem for the file names - or just use theirs?

**Comment by mguidoti** [comment]
We've been using one, that you helped to define long time ago: `JournalName.volume.issue.firstPage-lastPage.pdf`

**Comment by Carol-Sokolowicz** [comment]
It's uploaded:
https://zenodo.org/record/3744689
http://treatment.plazi.org/GgServer/summary/FFEF437EA013FFD7C944FF97FFB2FFA0

**Comment by mguidoti** [comment]
Thanks, @Carol-Sokolowicz !

Here's the GBIF link too: https://www.gbif.org/dataset/a270ab31-7e52-4655-aaa4-55d34fcf7fb3
