### ISSUE TITLE
Incomplete treatments

### ISSUE THREAD

**Issue by ChrFerrer** [plazi/community#252]
The following treatments are incomplete (lacking text, material examined, description, ect..):
* https://treatment.plazi.org/id/4148D212-040F-FF8C-FF33-FF5576EB10E0
* https://treatment.plazi.org/id/4148D212-040C-FF8F-FF33-FEBD76E81198
* https://treatment.plazi.org/id/4148D212-044C-FFCF-FF33-FDE976F91254
* https://treatment.plazi.org/id/4148D212-0406-FF85-FF33-FC1876EB1424
* https://treatment.plazi.org/id/4148D212-045D-FFDE-FF33-FBD176F9146C
* https://treatment.plazi.org/id/4148D212-040C-FF8F-FF33-FEBD76E81198
* https://treatment.plazi.org/id/4148D212-0442-FFC1-FF33-FA5576F915E0
* https://treatment.plazi.org/id/4148D212-046F-FFEC-FF33-FD3076E8130C
* https://treatment.plazi.org/id/4148D212-0418-FF9B-FF33-FB6E76EB14D6
* https://treatment.plazi.org/id/4148D212-0461-FFE2-FF33-FF2C745B1174 (also wrong title, it should be "Ophiomusium lymani Thomson, 1873")

**Comment by valdenar** [comment]
Hi @ChrFerrer,
I corrected the treatments. (BD71AA6A0450FFD3FFA4FFCD76121037)
If you need any more changes, please let me know.

Best regards

Valdenar

**Comment by gsautter** [comment]
What exactly am I supposed to help understand? How would you expect a treatment UUID to behave if a treatment has been deleted? Should there be any special handling for deleted duplicates?

**Comment by myrmoteras** [comment]
first, the treatments should not disappear, because they have been treatments that have not been complete, but missing parts.

If they are duplicates, then we need to be able to link them to the currentyl valid treatment. It seems not be correct, that  something disappears.  In this case, Ferrer builds a databae that includes links to our treatments. They should not break.

Not sure, whether @valdenar is aware of this, and what he did to fix this bug - but we need to have a description what to do in this case. (also @flsimoes ). May be there is a way to fix this treatment without creating new ones?

**Comment by valdenar** [comment]
@myrmoteras What I did was I opened each of the links in the issue, then I opened the paper in GGI and found each treatment referring to the links in the issue and then I made the correction. I saved and waited for the links to update. Here is the link to the paper's TB https://treatment.plazi.org/GgServer/summary/BD71AA6A0450FFD3FFA4FFCD76121037 and here is the link to one of the treatments https://treatment.plazi.org/GgServer/html/4148D2120461FFE2FF33FEE4723313EC
This monograph has not yet gone through Quality Control.

**Comment by valdenar** [comment]
@myrmoteras the treatments already existed so I extended their bounds, removed the existing subSubSections and ran the treatment structure to assign new subSubSections to the entire treatment. In the case where the nomenclature was in the wrong taxonName I adjusted the treatment limits. To adjust the treatment limits I clicked on split treatment and deleted the part that didn't belong to the treatment and then corrected the subSubSection.

**Comment by gsautter** [comment]
> @gsautter what is happening if you extend a treatment boundary? will this create a new treatment ID?

Indeed it does, as the UUID is computed from the annotation type, the page IDs of the first and last word, the top left of the first word, and the bottom right of the last word, and all of that XORed with the article UUID.

While this does effect a UUID change if the boundaries change, it on the is well-defined and reproducible, i.e., removing a treatment and re-adding it in the same position recreates the same UUID ... the latter would not be possible with random UUIDs, so overall, this well-defined approach is more stable.

**Comment by myrmoteras** [comment]
ok - but with that we do not guarantee a persistent treatment identifier and break our promis. 

Does this also mean, that the treatment in BLR will change?

Does it have an effect on material citation in GBIF? will they also be disbandened because of the new treatment?

is there
* a way to keep the treatmentUUID if there is one?
* to create an attribute including the previous treatment UUID

**Comment by gsautter** [comment]
> ok - but with that we do not guarantee a persistent treatment identifier and break our promis.

Only in rare cases ... such boundary changes don't happen very frequently, far as I know, and even more rarely after QC, and only then should the treatments go out to GBIF, BLR, etc.

> Does this also mean, that the treatment in BLR will change?

If the textual extent is wrong, it most likely should ... using the `-2` trick. The old BLR treatment will have a link to the new one, though, as the exporter handles the `-2` signal that way.

> Does it have an effect on material citation in GBIF? will they also be disbandened because of the new treatment?

The `taxonID` will change, yes, but _not_ the materials citation IDs proper (only their treatment UUID prefix), as the UUIDs of the materials citations are computed the same way as those of the treatments proper, independent of any surrounding annotations.

> is there
> 
>     * a way to keep the treatment UUID if there is one?

Tough one ... we might make sure to forward any old treatment UUID to the one that replaced it, though, as sort of a tombstone service, akin to the forwarding mechanism in BLR.

Physically retaining any UUID in some way might even be possible technically, but that would incur a swath of downstream problems:
- what if you _want_ to replace a UUID, e.g. early on in QC, before the treatment gets distributed?
- what if you split a treatment into multiple ones? which part should retain the existing UUID?
- what if you merge multiple treatments? which of the UUIDs should the resulting treatment take?

>     * to create an attribute including the previous treatment UUID

I don't think an attribute will do the trick, even though we might add one ... how would that handle multiple boundary changes, for instance? Plus, in case you remove and re-add a treatment, while the computed UUID is reproducible (see above), such an attribute would be lost ... a centralized tombstone service feels like the better option to me, especially since such a service could also provide an associated resolver endpoint, which we need anyway to make any sensible use of whichever way we retain any obsolete treatment UUIDs.

**Comment by flsimoes** [comment]
> first, the treatments should not disappear, because they have been treatments that have not been complete, but missing parts.
> 
> If they are duplicates, then we need to be able to link them to the currentyl valid treatment. It seems not be correct, that something disappears. In this case, Ferrer builds a databae that includes links to our treatments. They should not break.
> 
> Not sure, whether @valdenar is aware of this, and what he did to fix this bug - but we need to have a description what to do in this case. (also @flsimoes ). May be there is a way to fix this treatment without creating new ones?

As far as I'm aware the way Valdenar fixed it should have kept the UUID attached to that treatment. We've not had this problem before, unless my memory fails me. Not sure what happened here

**Comment by gsautter** [comment]
> As far as I'm aware the way Valdenar fixed it should have kept the UUID attached to that treatment. We've not had this problem before, unless my memory fails me. Not sure what happened here

As long as the first and last word don't change, the UUIDs remain the same, true, but if either one or both change, the UUID inevitably changes as well, simply as a consequence of how the data model defines and computes UUIDs for annotations (see my earlier comment) ... in this sense, a tombstone service does make sense ... already thinking about it, also in terms of reconstructing the tombstones retrospectively.

**Comment by flsimoes** [comment]
> > As far as I'm aware the way Valdenar fixed it should have kept the UUID attached to that treatment. We've not had this problem before, unless my memory fails me. Not sure what happened here
> 
> As long as the first and last word don't change, the UUIDs remain the same, true, but if either one or both change, the UUID inevitably changes as well, simply as a consequence of how the data model defines and computes UUIDs for annotations (see my earlier comment) ... in this sense, a tombstone service does make sense ... already thinking about it, also in terms of reconstructing the tombstones retrospectively.

ah ok, I thought it only affected the zenodo deposition

**Comment by gsautter** [comment]
> ah ok, I thought it only affected the zenodo deposition

Nope ... and in fact, the Zenodo deposition number does _not_ change unless you set it to `-2` to have the deposition recreated to reflect the rectified treatment boundaries in the HTML representation.

**Comment by ChrFerrer** [comment]
Thanks to have somehow repaired the treatments, I got the new IDs. Definitely yes, if it is possible to keep a stability of treatment IDs it's the best, especially for potential use in databases not updated automatically. Regards.

**Comment by gsautter** [comment]
The treatment HTTP URIs should resolve again now, we have an operational redirect service for UUIDs that change due to annotation boundary modifications, including splitting and merging treatments.

Treatments removed as duplicates (renamed to `treatmentDuplicate`) are also picked up by the component that provides the redirects, but not redirected to anything at this point, as finding out the replacement UUID is much more complicated in that scenario.

We will also have to think about what removed treatments should redirect to, i.e., treatments that were removed because their content isn't an actual treatment at all ... potentially sort of a fixed tombstone page or something similar ... suggestions welcome.

**Comment by gsautter** [comment]
PS: It might be another day or two until said UUID redirect service covers each and every treatment UUID we ever had, as it is still digging through the publications ... going through every single version of every single one of them is a good bit of effort.
