### ISSUE TITLE
GBIF datasets - a request for a default value when Collection code not provided in the article

### ISSUE THREAD

**Issue by spalp** [plazi/community#261]
To correctly map occurrences from a dataset to a collection in [GRSciColl](https://scientific-collections.gbif.org/collection/search), we need a value in the field _Collection code_.
Is it possible on your side, in cases where _Collection code_ is not provided/filled in, to replace by default the available value for _Institution code_? And vice versa - could the missing value for _Institution code_ be replaced with the available value of the _Collection code_?
For example, in the occurrence: https://www.gbif.org/occurrence/4097195321, the _Institution code_ is 'BFUS' and there is no value for _Collection code_. I would like the value of _Collection code_ to be filled in with 'BFUS'.
For the following occurrence: https://www.gbif.org/occurrence/2999483405, there is already a _Collection code_ and _Institution code_ provided, thus no action is needed.

**Comment by flsimoes** [comment]
I've forwaded your question to our developer
Please bear with us a little bit

**Comment by flsimoes** [comment]
@spalp 

the underlying problem is that the publications we extract the materials citations from hardly ever provide both of `institutionCode` and `collectionCode` and authors seem to use them somewhat interchangeably, so it's even hard to tell which one any give acronym represents ... to exacerbate the issue, specimen codes are far from always present, even though they seem to be becoming more frequent in more recent publications.

Defaulting the `institutionCode` and `collectionCode` to one another on data export is in so far problematic as it would pretend a level of detail information that simply isn't there. While such defaulting sure makes sense for certain applications, I think this should happen on the consuming side, so the consuming application is aware of the defaulting behavior, and it can be considered when interpreting results.

**Comment by spalp** [comment]
@flsimoes 
Thank you very much for your feedback. I see your point. I will contact our data team to see what they can do about this issue.

**Comment by ManonGros** [comment]
Thanks @flsimoes I think we can try to work around that. The issue can be closed.
