### ISSUE TITLE
MAC: use GGI 

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#35]
Java Development Kit? Which one to download?

**Comment by myrmoteras** [comment]
@mguidoti ask guido. he and Torsten are trying to figure out - or better figured it out

**Comment by mguidoti** [comment]
I think Guido replied Torsten directly, and I wasn't involved. Do you know the answer, @myrmoteras, so we can document it here?

**Comment by gsautter** [comment]
Anything Java 1.6 or later should work, as I don't use any of the "fancy cool sexy features" introduced by any of the later versions (lambdas, etc.) because they compile into utterly inefficient code ... 
Java 1.8 is the last one that is "Java as it once was", as Java 1.9 changed the license, but that isn't relevant unless you _compile_ code (as opposed to _executing_ code compiled elsewhere).
