### ISSUE TITLE
Materials/reference_group in Catalogs

### ISSUE THREAD

**Issue by flsimoes** [plazi/community#38]
@myrmoteras

In some catalogs, the type material is cited among the reference_group, which obviously mean that the authors are just citing such material instead of actually having examined it. However, we are not sure how we should annotated these, simply because there are two different interpretations in place: a) that of GGI, which calls it `materials_examined` (which implies that authors actually examined the specimens), and b) that of GBIF, which calls it `materialsCitation` which would include even those specimens that weren't properly seen by authors.

In cases such as the one below, should we split the annotations? (i.e. `treatmentCitation` separated from `materialsCitation`)

![image](https://user-images.githubusercontent.com/3343086/81068671-1f174700-8eb7-11ea-9a9b-d1effaa9d6b1.png)

**Comment by myrmoteras** [comment]
MaterialsCitation can be many thing, so there is no clear definition. The important thing we can contribute however, is to make data about types accessible. In this regards, even though the author might not have looked at the type, and in fact he does not have to, because a holotype is fixed and can not be reinterpreted in regards of the link to the original description, I suggest to mark them up. This is a bigger service than a strict, non-enforceable definition of MC.

**Comment by mguidoti** [comment]
Hi @myrmoteras, just to make it clear: you want all **types** or only the **holotypes**?

Thanks

**Comment by flsimoes** [comment]
As per our understanding, feeding from other examples and from https://github.com/plazi/plazi-at-poa/wiki/Unofficial-Annotation-Granularity-Policy . Ideally we need to mark at least the highest available type for a given taxon (starting with holotype, then if the first isn't available, go on to marking a lectotype or neotype, for instance).
