### ISSUE TITLE
Where is the current GGI manual?

### ISSUE THREAD

**Issue by aubreymoore** [plazi/community#52]
The download link for the GGI manual on http://plazi.org/resources/treatmentbank/goldengate-editor/ points to a Google Doc which appears to have been last updated 2017-03-08, and this in turn suggests a Pro-iBiosphere doc which is even older (2016-11-27). 

I am trying to learn GGI and I am just wondering if these docs are still relevant.

**Comment by myrmoteras** [comment]
as baseline documents they are. More actul are all the movies. @flsimoes would know, where the teaching notes from last years training course are.

Great you make this effort. If you get stuck, please contact and I or somebody from the team can give you a hand via skype or zoom

**Comment by flsimoes** [comment]
@aubreymoore 
I'm attaching our Commented Steps Guide and our screencasts link

[GGI-Commented_Steps.pdf](https://github.com/plazi/community/files/5820648/GGI-Commented_Steps.pdf)

The guide is a few months old, so keep that in mind if things look a bit different, though most of it is still the same.

Screencasts: https://www.youtube.com/playlist?list=PLFbvkmnvLdUdGmmn8SR4xyRRxulvVu7BE

Bear in mind that these are not final versions and some things shown in the videos may look differently now, as GGI has gone through updates since they were recorded in early 2020.

If you have any questions, please do not hesitate to contact me directly here.
