### ISSUE TITLE
Plant specimens not parsed correctly creating bogus records in GBIF

### ISSUE THREAD

**Issue by rdmpage** [plazi/community#97]
I've looked at a couple of treatments for 2021-11-11 and there are obvious issues.

For https://tb.plazi.org/GgServer/html/03D287EDFF8E5E45FF08FF6F4B05F949 (see https://plazi-tester.herokuapp.com/?uri=03D287ED-FF8E-5E45-FF08-FF6F4B05F949 ) the parser treats initials as collection codes and most of the records added to GBIF are clearly wrong 9consisting of a collection code and little else).

Likewise https://tb.plazi.org/GgServer/html/03A68781E05F071BFD86ADF2FD3DFD01 (see https://plazi-tester.herokuapp.com/?uri=03A68781-E05F-071B-FD86-ADF2FD3DFD01 ) is less extreme but also generates spurious specimen codes.

These errors are pretty easy to catch by simply comparing the markup with the underlying text.

**Comment by flsimoes** [comment]
> For https://tb.plazi.org/GgServer/html/03D287EDFF8E5E45FF08FF6F4B05F949 (see https://plazi-tester.herokuapp.com/?uri=03D287ED-FF8E-5E45-FF08-FF6F4B05F949 ) the parser treats initials as collection codes and most of the records added to GBIF are clearly wrong 9consisting of a collection code and little else).

There are single-letter collectionCodes in botanical collections, so that's why we can get the eventual incorrect annotation in that regard.

> Likewise https://tb.plazi.org/GgServer/html/03A68781E05F071BFD86ADF2FD3DFD01 (see https://plazi-tester.herokuapp.com/?uri=03A68781-E05F-071B-FD86-ADF2FD3DFD01 ) is less extreme but also generates spurious specimen codes.

We'll check them. Thanks for pointing them out.

**Comment by rdmpage** [comment]
I understand, but these are clearly initials in people's names. And the Plazi web service parses that name correctly, e.g. https://tinyurl.com/2zc758tz

Also a simple visual check is enough to spot the errors. Can Plazi not implement something like a post-parsing quality check? The volume of results on a typical day is pretty small, so it shouldn't be too difficult.

**Comment by myrmoteras** [comment]
`The volume of results on a typical day is pretty small`

Yes and no. To understand what it takes to get to the material citation, please take your time and start from here: Is there a Phytotaxa on 2021-11-11? Then get the article and process so you have access to and can reuse the data in the article (summary in [html](https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+doc.doi+doc.gbifId+doc.zenodoDepId+bib.source+cont.treatCountDoi+cont.matCitCount+cont.figCountZen+cont.figCitCount+cont.bibRefCount+cont.bibRefDoiCount+cont.bibRefCitCount+cont.countries+mat.matCitCount&groupingFields=doc.articleUuid+doc.doi+doc.gbifId+doc.zenodoDepId+bib.source&FP-doc.doi=%2210.11646%2Fphytotaxa.525.1.8%22&format=HTML), [json](https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+doc.doi+doc.gbifId+doc.zenodoDepId+bib.source+cont.treatCountDoi+cont.matCitCount+cont.figCountZen+cont.figCitCount+cont.bibRefCount+cont.bibRefDoiCount+cont.bibRefCitCount+cont.countries+mat.matCitCount&groupingFields=doc.articleUuid+doc.doi+doc.gbifId+doc.zenodoDepId+bib.source&FP-doc.doi=%2210.11646%2Fphytotaxa.525.1.8%22&format=JSON)). This includes already a set of quality control steps we explained at the recent TDWG meeting (doi: [10.3897/biss.5.75432 ](https://doi.org/10.3897/biss.5.75432).

Any errors upstream will have a bigger effect than one downstream, such as processing and QC-in material citations, so they need to be corrected before data gets uploaded to BLR or GBIF.

The resources spend on any of these tasks have to be balanced to maintain our operations.

Any manual processes do not scale up and need to be optimized as much as possible. The errors you point out will help to correct. Better algorithms to find, parse material citations are highly appreciated and help to avoid these errors. Finally as pointed out before, unfortunately, the botanical community has their own one symbol collection codes which complicates the matter. The growing lists of person names will help to improve the algorithms, some of the them being built using even imperfect material citations submitted to GBIF.

With other words, the daily volume of new articles processed might look small, the overall production of processing backlogs and quality control is not. 

If we would convince our authors to publish semantically enhanced, then we would not need to lead this discussion anymore - which we of course need looking at the legacy content with much less resolved material citations and huge issues with text recognition errors.

**Comment by myrmoteras** [comment]
`a simple visual check` tells that there is some information about a species published today, combined with a link that allows me to look at the original text and the entire treatment, may be even figures published in an article to which I have not necessarily access, neither have I had any other chance to become aware of.

This way round is for us more important than not knowing. There are ten thousands of species in GBIF that are only this way represented.

We also believe that this will lead to not only to the discussion we have on how we make taxonomic data accessible in a digital age. For sure not by publishing text strings in PDF, but by making people happy to be able to build tools to reuse the data without any data cleaning.

**Comment by rdmpage** [comment]
@myrmoteras I still feel that you are sidestepping the quality issue. Demonstrably some of the data produced by Plazi is incorrect. The response to this seems to be "but look at all the data we are liberating that wouldn't otherwise be available". The quantity of data isn't the issue, it's the **quality**. Criticism of quality is mostly met with deflection (e.g., explanations of the process, or the goals of Plazi, etc.) rather than addressing the issue.

I find it frustrating that Plazi seems determined not to take any responsibility for this issue. I understand that the task is challenging, but it's a task Plazi itself has decided to take on. Surely a part of the tax process would involve checks that the data generated is as good as it can be?

**Comment by myrmoteras** [comment]
Yes, data that we extract from text can be wrong at many levels. It has been published for human consumption, and is a citation of  an  occurrence of specimen or sample. 

We are already happy, that you spend time to criticize us, similar to years ago GBIF and its not fit for use occurrences therein. We are happy, because this means that data that is not otherwise accessible is being taken seriously - often the only data that exists about species.

You want quality that you define. This might or might not be same as we envision and deliver. For us, a first level of quality is that we can say, here is most likely a material citation in treatment of taxon X published in article Y. This allows to take this material citation, look at it both as human or machine, if not happy, access the source taxonomic treatment, have a look at the original article (if not closed access). It allows you to criticize, it allows you to notify us or curate the data if you want, or suggest better algorithms, or just take all the data an reanalyze it by yourself. 
It allows us to compare this with occurrences in GBIF, use GBIF clusters and analyse the results. Part of it is to understand why thing do not compare, are not in clusters and whether we can find patterns for it. It allows us to collect error data, analyse the errors and decide where to improve and invest. It guides on where we look for funding to improve this operation. It also allows to convince publishers to publish material citations differently so data can be annotated in more detail. We talk about the issue (see the last TDWG [Symposium](http://plazi.org/posts/tdwg-2021-virtual-annual-conference/)), we work with TDWG to create  MaterialCitation to separate the material citation from occurrences.

We believe that this adds a different quality to published species biodiversity data in comparison to when publishing geocoordinates extracted from publications on a map. 

Plazi is one of the data publishers that have a direct link to notify the publisher that there are data issues and which normally is being taken care of within days including the republishing.

You can be frustrated about Plazi - but that does not mean we are not determined to take things seriously and are ingenious about it. Just one step after the other.
